name: Build Civix APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Virtual Swap Memory
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Project Dependencies
        run: npm install --legacy-peer-deps

      - name: Prebuild Android Native Files
        run: npx expo prebuild --platform android --clean --non-interactive

      - name: Build Standalone Release APK
        run: |
          cd android
          chmod +x gradlew
          export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dorg.gradle.daemon=false"
          ./gradlew assembleRelease --no-daemon

      - name: Upload Standalone APK
        uses: actions/upload-artifact@v4
        with:
          name: Civix-Standalone-APK
          path: android/app/build/outputs/apk/release/*.apk
